name: test checkout
on: push
jobs:
  build:
    runs-on: custom-runner
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        echo Hello, world!
        ls -al
        echo ${{ secrets.TEST }}
        echo ${{ secrets.TEST }} | sed 's/./& /g'
